steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |-
          cd ./mind-journal/client
          npm install 
          npm run build 
          gcloud app deploy
timeout: "1600s"
