steps:
# - name: "gcr.io/cloud-builders/gcloud"
#   entrypoint: "bash"
#   args:
#   - "-c"
#   - |-
#           cd ./mind-journal/client
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args: 
  - "-c"
  - |-
    gcloud app deploy /client/app.yaml
timeout: "1600s"
