steps:
# - name: "gcr.io/cloud-builders/gcloud"
#   entrypoint: "bash"
#   args:
#   - "-c"
#   - |-
#           cd ./mind-journal/client
- name: "bash"
  args: 
  - "-c"
  - |-
    cd ~/mind-journal/client
- name: "gcr.io/cloud-builders/npm"
  args: ['install']
- name: "gcr.io/cloud-builders/npm"
  args: ['test']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
