steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |-
          cd ./client
- name: node:v16.0.0
  entrypoint: npm
  args: ['install']
- name: node:v16.0.0
  entrypoint: npm
  args: ['run', 'build']
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |-
          gcloud app deploy
timeout: "1600s"
