steps:
# - name: "gcr.io/cloud-builders/gcloud"
#   entrypoint: "bash"
#   args:
#   - "-c"
#   - |-
#           cd ./mind-journal/client
# - name: "gcr.io/cloud-builders/gcloud"
#   entrypoint: "bash"
#   args: 
#   - "-c"
#   - |-
#     gcloud app deploy client/app.yaml
# frontend deployment
# Step 1: For installing dependencies
  - name: "gcr.io/cloud-builders/npm"
    dir: 'client'
    args: ["install"]

# Step 2: For creating optinimized build
  - name: "gcr.io/cloud-builders/npm"
    dir: 'client'
    args: ["run", "build"]

# Step 3: This step will execute app.yaml in your ui folder and deploy your app based on the configuration specified
  - name: "gcr.io/cloud-builders/gcloud"
    dir: 'client'
    args: ["app", "deploy"]
timeout: "1600s"
